spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jastalant}
spring.datasource.username=${DB_USERNAME:jastalant}
spring.datasource.password=${DB_PASSWORD}
spring.mail.port=${SMTP_PORT:1025}
app.auth.refresh-cookie-secure=false
